blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired
#from wtforms import ValidationError
#from flask_wtf.file import FileField, FileAllowed


class BlogPostForm(FlaskForm):
	title = StringField('Title',validators=[DataRequired()])
	text  = TextAreaField('Body',validators=[DataRequired()])
	submit = SubmitField("Published Post")

blog/core/views.py
# Core/views.py
from flask import render_template,request,Blueprint
from blog.models import BlogPost

core = Blueprint('core',__name__)

@core.route('/')
def index():
	page = request.args.get('page',1,type=int)
	posts = BlogPost.query.order_by(BlogPost.created_at.desc()).paginate(page=page,per_page=4)
	return render_template('index.html',posts=posts)

@core.route('/about')
def about():
	return render_template('about.html')

blog/posts/views.py
# posts/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import current_user,login_required
from blog import db
from blog.models import BlogPost
from blog.posts.forms import BlogPostForm


posts = Blueprint('posts',__name__)

# create
@posts.route("/create",methods=['GET','POST'])
@login_required
def create_post():
	form = BlogPostForm()
	if request.method == 'POST' and form.validate() and form.validate_on_submit():
		blog_post = BlogPost(title=form.title.data,text=form.text.data,user_id=current_user.id)
		db.session.add(blog_post)
		db.session.commit()
		flash('Post Created')
		return redirect(url_for('core.index'))
	return render_template('create_post.html',form=form)


# View Post
@posts.route("/<int:post_id>",methods=['GET','POST'])
def post(post_id):
	post = BlogPost.query.get_or_404(post_id)
	return render_template('post.html',post=post)

# Update
@posts.route("/<int:post_id>/update",methods=['GET','POST'])
@login_required
def update_post(post_id):
	post = BlogPost.query.get_or_404(post_id)
	if post.author != current_user:

		abort(403)

	form = BlogPostForm()
	if form.validate_on_submit():
		post.title = form.title.data
		post.text = form.text.data
		db.session.commit()
		flash('Post Updated')
		return redirect(url_for('posts.post', post_id=post.id))

	elif request.method == 'GET':
		form.title.data = post.title
		form.text.data = post.text
		return render_template('create_post.html', title='Update',form=form)

# Delete
@posts.route("/<int:post_id>/delete",methods=['GET','POST'])
@login_required
def delete_post(post_id):
	post = BlogPost.query.get_or_404(post_id)
	if post.author != current_user:
		abort(403)
	db.session.delete(post)
	db.session.commit()
	flash('Post Deleted')
	return redirect(url_for('core.index'))

blog/users/views.py
# users/views.py
from flask import render_template,url_for,flash,redirect,request,Blueprint
from flask_login import login_user,current_user,logout_user,login_required
from blog import db
from blog.models import User,BlogPost
from blog.users.forms import LoginForm,RegistrationForm,UpdateuserForm
from blog.users.picture_handler import add_profile_pic

users = Blueprint('users',__name__)

#register
@users.route("/register",methods=['GET','POST'])
def register():
	form = RegistrationForm()
	error = None;
	if request.method == 'POST' and form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user:
			error = "Email Already Exists"
		else:
			user = User(email=form.email.data,
						username=form.username.data,
						password=form.password.data)
			db.session.add(user)
			db.session.commit()
			flash('Thanks For Registration','regi_success')
			return redirect(url_for('users.login'))

	return render_template('register.html',form=form,error=error)
#login
@users.route("/login",methods=['GET','POST'])
def login():
	form = LoginForm()
	error = None
	if form.validate_on_submit():
		user = User.query.filter_by(email=form.email.data).first()
		if user:
			if user.check_password(form.password.data) and user is not None:
				login_user(user)
				flash('Log in Success','login_success')
				next = request.args.get('next')
				if next == None or not next[0] == '/':
					next = url_for('core.index')
				return redirect(next)
			else:
				error = 'Password DoesNot Match'
		else:
			error = 'No User Found'

	return render_template('login.html',error=error,form=form)

#logout
@users.route("/logout")
def logout():
	logout_user()
	return redirect(url_for("core.index"))

#account
@users.route("/account",methods=['GET','POST'])
@login_required
def account():
	form = UpdateuserForm()
	if form.validate_on_submit():
		if form.picture.data:
			username =  current_user.username
			pic = add_profile_pic(form.picture.data,username)
			current_user.profile_image = pic
		current_user.username = form.username.data
		current_user.email = form.email.data
		db.session.commit()
		flash('User Account Updated')
		return redirect(url_for('users.account'))
	elif request.method == 'GET':
		form.username.data = current_user.username
		form.email.data    = current_user.email
	profile_image = url_for('static',filename='profile_pics/' + current_user.profile_image)
	return render_template('account.html',profile_image=profile_image,form=form)





#users Blog Posts
@users.route("/<username>")
def user_posts(username):
	page = request.args.get('page',1,type=int)
	user = User.query.filter_by(username=username).first_or_404()
	blog_posts = BlogPost.query.filter_by(author=user).order_by(BlogPost.created_at.desc()).paginate(page=page,per_page=5)
	return render_template('user_blog_post.html',blog_posts=blog_posts,user=user)

blog/templates/about.html
{% extends "base.html" %}

{% block content %}
    		<div class="jumbotron mt-3">
    			<h1 class="display-3">Info About Our Company!</h1>
    			<p>
    				Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eveniet quisquam officia cumque. Dicta consectetur animi, amet recusandae tempore corporis labore ipsa. Non minima illum nostrum quam molestiae reiciendis, porro animi!
    			</p>
			</div>
{% endblock content %}

blog/templates/account.html
{% extends "base.html" %}
{% block content %}
    <div class="jumbotron">
       <div align="center">
           <h1>Welcome to The Page for {{current_user.username}}</h1>
           <img align="center" src="{{url_for('static',filename='profile_pics/'+current_user.profile_image)}}">
       </div>
    </div>
    <div class="container">
    	<form method="POST" enctype="multipart/form-data">
    		{{form.hidden_tag()}}
    		<div class="form-group">
    			{{form.username.label(class='form-group')}}
    			{{form.username(class='form-control')}}
    		</div>
    		<div class="form-group">
    			{{form.email.label(class='form-group')}}
    			{{form.email(class='form-control')}}
    		</div>
    		<div>
    			{{form.picture.label(class='form-group')}}
    			{{form.picture}}
    		</div>
    		<div class="form-group">
    			{{form.submit(class='btn btn-dark btn-block')}}
    		</div>

    	</form>
    </div>
{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{{url_for('core.index')}}">Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{{url_for('core.about')}}">About</a>
      </li>
      {% if current_user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('posts.create_post')}}">Create Post</a>
            </li>

            <li class="nav-item">
            <a class="nav-link" href="{{url_for('users.account')}}"">Account</a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.logout')}}">Logout</a>
            </li>
      {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.login')}}"">Log In</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{url_for('users.register')}}"">Register</a>
            </li>
      {% endif %}


    </ul>
  </div>
</nav>

<div class="container">
  {% block content %}

{% endblock content %}
</div>

<!-- jQuery first, then Popper.js and Bootstrap JS. -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
</body>
</html>

blog/templates/create_post.html
{% extends "base.html" %}

{% block content %}
   <div class="container">
   	  <form method="POST">
   	  	{{form.hidden_tag()}}
   	  	<div class="form-group">
   	  		{{form.title.label(class='form-control-label')}}
   	  		{{form.title(class='form-control')}}
   	  	</div>

   	  	<div class="form-group">
   	  		{{form.text.label(class='form-control-label')}}
   	  		{{form.text(class='form-control')}}
   	  	</div>
   	  	<div class="form-group">

   	  		{{form.submit(class='btn btn-dark btn-block')}}
   	  	</div>
   	  </form>
   </div>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}

{% block content %}
    		<div class="jumbotron mt-3">
    			<h1 class="display-3">Hello,WellCome To Our Company!</h1>

    		</div>
    		<div class="container">
    			{% for post in posts.items %}
          		<div class="card">

          			<div class="card-block">
          				<h4 class="card-title"><a href="{{url_for('posts.post',post_id=post.id)}}">{{post.title}}</a>
          				 Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a></h4>
          				<p class="card-text">Published On: {{post.created_at.strftime('%y-%m-%d')}}</p>
          				<a href="{{url_for('posts.post',post_id=post.id)}}" class="btn btn-info">Read Post</a>
          			</div>
          		</div>
    			{% endfor %}
    		</div>


		<div class="col-md-6 mx-auto mt-3">
			<nav>
	          <ul class="pagination">
	            {% for page_num in posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
	               {% if posts.page == page_num %}
	                  <li class="page-item disabled"><a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a></li>
	                {% else %}
	                   <li class="page-item"><a class="page-link" href="{{url_for('core.index',page=page_num)}}">{{page_num}}</a></li>
	                {% endif %}
	            {% endfor %}
	          </ul>
	        </nav>
		</div>


{% endblock content %}

blog/templates/login.html
{% extends "base.html" %}
{% block content %}
	<div class="col-md-6 mx-auto mt-3">
		<h1>Login Form</h1>

		{% with messages = get_flashed_messages(category_filter=["regi_success"]) %}
		  {% if messages %}
			{% for message in messages %}
		      <p class="text-success">{{ message }}</p>
		    {% endfor %}
			{% endif %}
		{% endwith %}

		{% if error %}
		    <p class=text-danger><strong>Error:</strong> {{ error }} </p>
		{% endif %}

	    <form method="POST">
			{{form.hidden_tag()}}
			<div class="form-group">
				{{form.email.label(class='form-group')}}{{form.email(class='form-control')}}
			</div>
	        <div class="form-group">
	        	{{form.password.label(class='form-group')}}{{form.password(class='form-control')}}
	        </div>
	        <div class="form-group">
	        	{{form.submit(class='btn btn-dark btn-block')}}
	        </div>

	    </form>
	</div>
{% endblock content %}

blog/templates/post.html
{% extends "base.html" %}

{% block content %}
   <div class="jumbotron">
    <h1>{{post.title}}</h1>
    <h2>Written by: {{post.author.username}}</h2>
    <h3>Published: {{post.created_at.strftime('%B %d, %Y')}}</h3>
    <p>{{post.text}}</p>

    {% if post.author == current_user %}
        <div>
        	<a class="btn btn-info btn-xs" href="{{url_for('posts.update_post',post_id=post.id)}}">Update</a>
        	<button class="btn btn-danger btn-xs" data-toggle="modal" data-target="#del_modal">Delete</button>
        </div>
    {% endif %}
   </div>

   		<div class="modal fade" id="del_modal">
   			<div class="modal-dialog" role="document">
   				<div class="modal-content">
   					<div class="modal-header">
   						<button type="button" class="close" data-dismiss="modal" aria-label="Close">
   							<span aria-hidden="true">&times;</span>
   							<span class="sr-only">Close</span>
   						</button>
   						<h4 class="modal-title">Delete Post?</h4>
   					</div>
   					<div class="modal-body">
   						<p>Are You Sure?</p>
   					</div>
   					<div class="modal-footer">
   						<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
   						<form action="{{url_for('posts.delete_post',post_id=post.id)}}">
   							<input class="btn btn-danger btn-xs" type="submit" value="Delete">
   						</form>

   					</div>
   				</div><!-- /.modal-content -->
   			</div><!-- /.modal-dialog -->
   		</div><!-- /.modal -->
{% endblock content %}

blog/templates/register.html
{% extends "base.html" %}
{% block content %}
    <div class="col-md-6 mx-auto mt-3">

    	<h1>Registration Form</h1>
    	{% if error %}
		    <p class=text-danger><strong>Error:</strong> {{ error }} </p>
		{% endif %}
    	<form method="POST">
		{{form.hidden_tag()}}
		<div class="form-group">
			{{form.email.label(class='form-group')}}
			{{form.email(class='form-control')}}
			{% if form.password.email  %}

		    {% for error in form.password.email %}
		      <p class="text-danger">{{ error }}</p>
		    {% endfor %}

			{% endif %}
		</div>

		<div class="form-group">
			{{form.username.label(class='form-group')}}
			{{form.username(class='form-control')}}
			{% if form.password.username %}

		    {% for error in form.password.username %}
		      <p class="text-danger">{{ error }}</p>
		    {% endfor %}

			{% endif %}
		</div>

		<div class="form-group">
			{{form.password.label(class='form-group')}}
			{{form.password(class='form-control')}}

			{% if form.password.errors %}

		    {% for error in form.password.errors %}
		      <p class="text-danger">{{ error }}</p>
		    {% endfor %}

			{% endif %}
		</div>
		<div class="form-group">
			{{form.pass_confirm.label(class='form-group')}}
			{{form.pass_confirm(class='form-control')}}
		</div>

		<div class="form-group">
			{{form.submit(class='btn btn-dark btn-block')}}
		</div>

		</form>
    </div>
{% endblock content %}

blog/templates/user_blog_post.html
{% extends "base.html" %}
{% block content %}
    <div class="container">
        <div class="jumbotron">
            <div align="center">
                <h1>WelCome to the page for {{user.username}}</h1>
                <img src="{{url_for('static',filename='profile_pics/'+user.profile_image)}}">
            </div>
        </div>

      {% for post in blog_posts.items %}
       <h2><a href="{{url_for('posts.post',post_id = post.id)}}">{{post.title}}</a></h2>
       Written By: <a href="{{url_for('users.user_posts',username=post.author.username)}}">{{post.author.username}}</a>
       <p class="text-muted">Published On: {{post.created_at.strftime("%Y-%m-%d")}}</p>
       <br>
       <p>{{post.text}}</p>
      {% endfor %}


    </div>

        <nav>
          <ul class="pagination">
            {% for page_num in blog_posts.iter_pages(left_edge=1,right_edge=1,left_current=1,right_current=2) %}
               {% if blog_posts.page == page_num %}
                  <li class="page-item disabled"><a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a></li>
                {% else %}
                   <li class="page-item"><a class="page-link" href="{{url_for('users.user_posts',username=user.username,page=page_num)}}">{{page_num}}</a></li>
                {% endif %}
            {% endfor %}
          </ul>
        </nav>

{% endblock content %}